class BaseException

{

    public:

    virtual void printError()

    {

    }

};

class NullPointerException :public BaseException

{

    public:

    virtual void printError()

    {

        cout << "空指针异常" << endl;

    }

};

class OutOfRangeException :public BaseException //越界

{

    public:

    virtual void printError()

    {

        cout << "越界异常" << endl;

    }

};

void dowork()

{

    //throw NullPointerException();

    throw OutOfRangeException();

}

void test1()

{

    try

    {

        dowork();

    }

    catch(BaseException & e)

    {

        e.printError();

    }



}

